socialNetwork/profiles/urls.py
from collections import namedtuple
from django.urls import path
from .views import ProfileDetailView, ProfileListView, follow_unfollow_profile, invite_profiles_list_view, invites_received_view, my_profile_view, profiles_list_view

app_name = 'profiles'

urlpatterns = [
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('myprofile/', my_profile_view, name='my-delete-view'),
    path('my-invitations/', invites_received_view, name='my-invitations-view'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('', follow_unfollow_profile, name='follow-unfollow-profile'),
    
]

socialNetwork/socialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

socialNetwork/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.shortcuts import render
from .utils import get_random
from django.template.defaultfilters import slugify
from django.db.models import Q

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.sender)
                accepted.add(rel.receiver)

        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)

        return available
        


    def get_all_profiles(self,me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="Hello!...", max_length=400)
    email = models.EmailField(max_length=200, blank=True)
    location = models.CharField(max_length=200, blank=True)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    followers = models.ManyToManyField(User, blank=True, related_name='followers')
    followings = models.ManyToManyField(User, blank=True, related_name='followings')
    slug = models.SlugField(blank=True, unique=True)
    edited = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)
    avatar = models.ImageField(default= 'avatar.png', upload_to='avatars/')

    objects = ProfileManager()

    def get_followers(self):
        return self.followers.all()
    
    def get_followers_num(self):
        return self.followers.all().count()
    
    def get_followings(self):
        return self.followings.all()
    
    def get_followings_num(self):
        return self.followings.all().count()

    def __str__(self):
        return f"{self.user}--{self.created}"

    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name)+ " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            
            while ex:
                to_slug= slugify(to_slug+" "+str(get_random()))
                ex = Profile.objects.filter(slug = to_slug).exists()

        else:
            to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args,**kwargs)

STATUS_CHOICES = (

    ('send', 'send'),
    ('accepted','accepted')

)

class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs
    

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    edited = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}--{self.receiver}--{self.status}"

socialNetwork/profiles/forms.py
from django import forms
from django.db.models import fields
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

socialNetwork/profiles/views.py
from django.db.models.query_utils import Q
from django.shortcuts import render, redirect
from django.urls import conf
from django.views.generic.detail import DetailView
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView


# Create your views here.

def follow_unfollow_profile(request):
    if request.method == "POST":
        my_profile = Profile.objects.get(user=request.user)
        pk = request.POST.get('profile_pk')
        obj = Profile.objects.get(pk=pk)

        if obj.user in my_profile.followings.all():
            my_profile.followings.remove(obj.user)
        else:
            my_profile.followings.add(obj.user)
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:all-profiles-view')


def my_profile_view(request):
    profile = Profile.objects.get(user= request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
            

    context = {
        'profile' : profile,
        'form' : form,
        'confirm' : confirm,
    }

    return render(request, 'profiles/myprofile.html', context)

def my_delete_view(request):
    user= request.user
    qs = Profile.objects.delete(user)

    context = {
        'qs': qs
    }

    return render(request, 'accounts/signup.html', context)

def invites_received_view(request):
    profile = Profile.objects.get(user= request.user)
    qs = Relationship.objects.invitations_received(profile)

    context = {
        'qs': qs
    }

    return render(request, 'profiles/my_invitations.html', context)


def invite_profiles_list_view(request):
    user= request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)

    context = {
        'qs': qs
    }

    return render(request, 'profiles/to_invite_list.html', context)

def profiles_list_view(request):
    user= request.user
    qs = Profile.objects.get_all_profiles(user)

    context = {
        'qs': qs
    }

    return render(request, 'profiles/profile_list.html', context)

class ProfileListView(ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile
        return context

class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profiles/detail.html'

    def get_object(self, **kwargs):
        pk = self.kwargs.get('pk')
        view_profile = Profile.objects.get(pk=pk)
        return view_profile

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        view_profile = self.get_object()
        my_profile = Profile.objects.get(user=self.request.user)
        if view_profile.user in my_profile.followings.all():
            follow = True
        else:
            follow = False
        context['follow'] = follow
        return context
    

socialNetwork/profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
Profile Detail
{% endblock title%}

{% block content %}
<!--Modal-->
<div class="ui basic modal " style="top:200px; height:400px">
    <div class="ui icon header">
      <i class="user plus icon"></i>
      Are you sure you want to follow {{object.user}}?
    </div>
    <div class="content">
      <p>By clicking 'Yes' you will be following {{object.user}}</p>
    </div>
    <div class="actions">
        <form action="{% url 'profiles:follow-unfollow-profile' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value={{object.pk}}>
            <button type="submit" class="ui green ok massive button">
                <i class="checkmark icon"></i>
                Yes
              </button>
        </form>
      
    </div>
  </div>
<div class="ui grid">
    <div class="row">
        
        <div class="four wide column">
            <img class="ui small circular image" src="{{object.avatar.url}}">
        </div>
        <div class="twelve wide column">
            <br>
            {{object}}
            <hr>
            {% if follow %}
                <form action="{% url 'profiles:follow-unfollow-profile' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative button">Unfollow</button>
                </form>
            {% else %}
                <button id="follow-btn" class="ui positive button">Follow</button>
            {% endif %}
        </div>
        
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        $('#follow-btn').click(function(){
            $('.ui.basic.modal')
            .modal('show')
            ;
            
        })
    })
</script>
{% endblock scripts %}

socialNetwork/profiles/templates/profiles/my_invitations.html
{% extends 'base.html' %}

{% block title %}
My Invitations
{% endblock title%}

{% block content %}
    <ul>
        {% for item in qs%}
        <li>
            {{item}}
        </li>
        {% endfor %}
    </ul>
{% endblock content %}

socialNetwork/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
My Profile
{% endblock title %}

{% block content %}
<!--Modal-->
<div class="ui modal mymodal">
    <i class="close icon"></i>
    <div class="header">
      Edit Your Profile
    </div>
    <div class="image content">
      <div class="ui medium image">
        <img src="{{profile.avatar.url}}">
      </div>
      <div class="description">
        <div class="ui header">Provide additional/newest info about you</div>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
        
      </div>
    </div>
    <div class="actions">
        <button class="ui negative right labeled icon button" onclick="profiles:my-delete-view">
            Delete Account
            <i class="checkmark icon"></i>
        </button>
      <button class="ui positive right labeled icon button">
        Edit Profile
        <i class="checkmark icon"></i>
      </button>
      

       </form>
        
      </div>
</div>




<div class="ui segment">
    {% if confirm2 %}
        <div class="ui red message">Your profile has been deleted</div>
    {% endif %}
    {% if confirm %}
        <div class="ui teal message">Your profile has been edited</div>
    {% endif %}
    
    <h3>My Profile: {{request.user}}</h3>
    <div class="ui grid">
        <div class="row">
            <div class="six wide column">
                <img class="ui medium rounded image" src={{profile.avatar.url}}>
                <div class="row mt-5">
                    <button class='ui secondary button' id='modal-btn' style="background-color: rgb(27, 151, 151);">Edit Your Profile</button>
                </div>
                

            </div>

            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>
                                username
                            </td>
                            <td>{{profile.user}}</td>
                        </tr>
                        <tr>
                            <td>
                                firstname
                            </td>
                            <td>{{profile.first_name}}</td>
                        </tr>
                        <tr>
                            <td>
                                lastname
                            </td>
                            <td>{{profile.last_name}}</td>
                        </tr>
                        <tr>
                            <td>
                                bio
                            </td>
                            <td>{{profile.bio}}</td>
                        </tr>
                        <tr>
                            <td>
                                follower number
                            </td>
                            <td>{{profile.get_followers_num}}</td>
                        </tr>
                        <tr>
                            <td>
                                Followers
                            </td>
                            <td><ul>
                                {% for follower in profile.get_followers%}
                                <li>{{follower}}</li>
                                {% endfor %}
                            </ul></td>
                        </tr>
                        <tr>
                            <td>
                                following's number
                            </td>
                            <td>{{profile.get_followings_num}}</td>
                        </tr>
                        <tr>
                            <td>
                                Followings
                            </td>
                            <td><ul>
                                {% for following in profile.get_followings%}
                                <li>{{following}}</li>
                                {% endfor %}
                            </ul></td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>

{% endblock content %}

socialNetwork/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
All Profiles to Follow
{% endblock title%}

{% block content %}
{{profile}}
    <ul>
        {% for item in qs%}
        <li>
            {{item}}
            <br>
            <a href={% url 'profiles:profile-detail-view' item.pk %}>
                <button class="ui primary button" style="background-color:rgb(23, 161, 161);">See Profile</button>
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock content %}

socialNetwork/profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
Invite Friends
{% endblock title%}

{% block content %}
    <ul>
        {% for item in qs%}
        <li>
            {{item}}
        </li>
        {% endfor %}
    </ul>
{% endblock content %}