socialNetwork/profiles/urls.py
from collections import namedtuple
from django.urls import path
from .views import ProfileDetailView, ProfileListView, follow_unfollow_profile, invite_profiles_list_view, invites_received_view, my_profile_view, profiles_list_view

app_name = 'profiles'

urlpatterns = [
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('myprofile/', my_profile_view, name='my-delete-view'),
    path('my-invitations/', invites_received_view, name='my-invitations-view'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('', follow_unfollow_profile, name='follow-unfollow-profile'),
    
]

socialNetwork/socialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

socialNetwork/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}
{{hello}}
<br>
{{user}}
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        console.log('Working')
    })
</script>
{% endblock scripts %}

socialNetwork/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}


<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="{{path_to_home}}" class=" {% if request.path == 'path_to_home' %}active{% endif %} item">
          <h3>Social Network</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="" class="item">
          Home
      </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal"> Users
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="{{path_to_all_profiles}}" class=" {% if request.path == path_to_all_profiles %}active{% endif %}item">
                          All Profiles
                      </a>
                      <a href="" class="item">
                          Followings
                      </a>
                      <a href="" class="item">
                          Followers
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="" method="GET">
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
          
              <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %}item">
                  <br>
                  <img src="{{picture.url}}" class="ui avatar image">&nbsp;
                   {{ request.user }}
              </a>
  
              <a href="{% url 'account_logout' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'account_login' %}" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>